resolver: lts-3.14
compiler: ghcjs-0.2.0.20151029_ghc-7.10.2
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.20151029_ghc-7.10.2:
        url: "https://github.com/nrolland/ghcjs/releases/download/v0.2.0.20151029/ghcjs-0.2.0.20151029.tar.gz"

packages:
- '.'

extra-deps:
  - ghcjs-dom-0.2.3.0

flags: {}
extra-package-dbs: []